services:
  rastame-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always      
    ports:
      - 9090:9090
    environment:
      - spring.ai.openai.api-key=
    volumes:
      - .m2:/root/.m2     